declare global {
  interface Window {
    showDirectoryPicker?: () => Promise<globalThis.FileSystemDirectoryHandle>
  }
}

export type AllowedMenu =
  | 'process'
  | 'data-compare'
  | 'xml-excel'
  | 'excel-csv-sqlite'
  | 'resume-ranking'
  | 'estimativas'
  | 'projeto-dev'
  | 'daily-activities'
  | 'digte-demands'
  | 'customer-hub'
  | 'customer-hub-dashboard'
  | 'customer-hub-clientes'
  | 'customer-hub-status-report'
  | 'customer-hub-contatos'
  | 'customer-hub-acessos'
  | 'customer-hub-sistemas'
  | 'customer-hub-processos'
  | 'customer-hub-historico'
  | 'central-servicos'
  | 'central-servicos-dashboard'
  | 'central-servicos-agenda'
  | 'central-servicos-atendimentos'
  | 'central-servicos-recursos'
  | 'central-servicos-contratos-servicos'
  | 'central-servicos-despesas'
  | 'central-servicos-faturamento'
  | 'central-servicos-pagamentos'
  | 'ticket-hub'
  | 'propostas'
  | 'rubricas-validacao'
  | 'rubrica-natureza'
  | 'rubrica-inc-cp'
  | 'rubrica-inc-fgts'
  | 'rubrica-inc-pis'
  | 'rubrica-inc-rpps'
  | 'rubrica-inc-irrf'
  | 'rubrica-dirf'
  | 'rubrica-id-calculo'
  | 'rubrica-regra'
  | 'rubrica-regra-comparacao'
  | 'user-admin'
  | 'change-password'

export {}
